### ISSUE TITLE
Plug-in No Longer Sees Purifiers

### ISSUE THREAD

**Issue by SawkeeReemo** [RaresAil/homebridge-levoit-air-purifier#72]
### Describe The Bug

It happened about a month ago, maybe. But my purifiers show “no response” in Home Kit. They worked perfectly fine, and I’ve had no problems with this plugin until recently. My VeSync credentials are correct. It just stopped working. Do I need to set up port forwarding for any reason? I recently disabled UPnP on my router for security reasons.

### Expected behavior

To work. 

### Logs

How do I get you logs for the plug-in? I don’t see that option anywhere.

### Plugin Config

        {
            "name": "Levoit",
            "email": "<redacted>",
            "password": "<pass-redacted>",
            "_bridge": {
                "username": "0E:3B:41:1B:17:D3",
                "port": 45492
            },
            "platform": "LevoitAirPurifiers"
        },

### Plugin Version

v1.3.1

### Homebridge Version

v1.6.1

### Node.js Version

v18.13.0

### NPM Version

 No clue. Whatever is installed with the Homebridge Docker image. I don’t see it listed in Homebridge.

### Operating System

Synology DSM 7.1.1-42962 Update 6

**Comment by RaresAil** [comment]
Hey @SawkeeReemo , do the purifiers work from homebridge dashboard? This issue occurred in the past due a homebridge issue, try updating the homebridge/server packages to latest and reboot, if the issue is still present, try this:

1. Set the email and password to "" and restart the child bridge (This will remove the accessories)
2. Add the email and password back and restart again

If this doesn't work, remove the accessories (step 1), uninstall the plugin, re install and re configure

**Comment by SawkeeReemo** [comment]
Thanks for the info. The steps didn't work for me as I couldn't figure out how to un/re-pair the child bridge without deleting the plugin and reinstalling. (Weird that Homebridge doesn't seem to give an option for this? Or maybe I just don't know where to find it, I checked everything I could think of.) But after completely removing the plugin, then reinstalling, I was immediately able to see the purifiers again.

Odd one, but at least it's back! Thanks again!
